### ISSUE TITLE
Add `--strict` option

### ISSUE THREAD

**Issue by deanWombourne** [kimdv/bitrise-step-swiftlint#3]
Hey.

It would be great to add a checkbox in the bitrise config which enabled the `--strict` command line option to the lint command. This would default to false, to keep backwards compatibility.

**Comment by kimdv** [comment]
Hi @deanWombourne  👋👋 sure that, I will look into that. Thanks 🙏 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by deanWombourne** [comment]
Hey - I decided that I should be a bit more proactive, so I've had a stab at fixing it myself. I've never coded anything for bitrise before, so I might be way off the mark :) Let me know what you think.

**Comment by kimdv** [comment]
@deanWombourne this is now merged in the Bitrise lib! 
Thanks for the help 🚀

**Comment by deanWombourne** [comment]
No worries :) Thanks for getting it in so fast!

**Comment by deanWombourne** [comment]
Hey - I've just updated the step in my bitrise workflow, and the dropdown for strict contains 3 values - 'false', 'false' and 'true' - have you ever seen this before? Looks like I didn't get it quite right :)

**Comment by kimdv** [comment]
Hey @deanWombourne !

How have you updated it? 
Using the step lib or referring via `git::https://github.com/kimdv/bitrise-step-swiftlint`

**Comment by kimdv** [comment]
@deanWombourne 

Please try to edit your `Bitrise.yml` with this block

```
    - git::https://github.com/kimdv/bitrise-step-swiftlint:
        inputs:
        - linting_path: "$BITRISE_SOURCE_DIR/BitBuild"
        - strict: 'yes'
        - reporter: emoji
```
